[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "aigc_motion_eval"
version = "0.0.1"
requires-python = ">=3.8"
dependencies = []

[tool.setuptools]
packages = ["motion_eval"]
